### ISSUE TITLE
Questions about the running configuration

### ISSUE THREAD

**Issue by ShiWuxuan** [scok30/vit-cil#3]
Thank you for your nice work and open source code. I want to know why the provided json configuration file uses Resnet-18 for backbone, while the paper mentions that it uses transformer?

**Comment by scok30** [comment]
Thank you for your attention to our work. In order to maintain a fair comparison and the fact that the vision transformer is not well known to converge in the incremental domain, one of our implementations is to directly combine it with the existing CNN model. Regarding your question, I am willing to compile a version of the vision transformer config for a clearer reference. Please wait for a while. Thank you
